#!/bin/bash
# This script is used to build and run the docker image for building AOSP.

IMAGE_NAME=aosp-build:latest
CONTAINER_NAME=aosp
PLATFORM="--platform linux/amd64"
DOCKERFILE=Dockerfile
MY_UID=$(id -u)
MY_NAME=$(id -un)

do_build() {
    echo "Building the docker image $IMAGE_NAME"
    set -x
    docker build $PLATFORM -t $IMAGE_NAME -f $DOCKERFILE .
    docker image prune -f
}

do_run() {
    [ -z "$1" ] && {
        echo "Usage: $0 run <aosp_dir>"
        exit 1
    }
    [ -d "$1" ] || {
        echo "The directory $1 does not exist."
        exit 1
    }
    echo "Run the docker container $CONTAINER_NAME"
    docker rm $CONTAINER_NAME &>/dev/null
    ABS_AOSP_DIR=$(realpath $1)
    set -ex
    # pass uid and name to `docker run` to ensure user-create run only once.
    docker run $PLATFORM --rm -d --name $CONTAINER_NAME -m 16g -h aosp -v $ABS_AOSP_DIR:/aosp -w /aosp $IMAGE_NAME $MY_UID $MY_NAME
}

do_bash() {
    set -x
    docker exec -it -u $MY_NAME $CONTAINER_NAME /bin/bash
}

do_stop() {
    echo "Stopping the docker container $CONTAINER_NAME"
    set -x
    docker stop $CONTAINER_NAME
}

do_clean() {
    echo "Cleaning up..."
    set -x
    # prune all dangling images
    docker image prune -f
    # prune all unused networks
    docker network prune -f
    # prune all unused volumes
    docker volume prune -f
    # show disk usage
    docker system df
}

#### Main ####

cd $(dirname $0)

action=$1
shift
case $action in
build)  do_build ;;
run)    do_run $@ ;;
bash)   do_bash ;;
stop)   do_stop ;;
clean)  do_clean ;;
*)
    echo "Usage: $0 {build|run <aosp_dir>|bash|stop|clean}"
    exit 1
    ;;
esac
